### ISSUE TITLE
Error on load and connection

### ISSUE THREAD

**Issue by ManuGooX** [Skungee/Skungee#130]
![image](https://user-images.githubusercontent.com/40543551/73581056-43aeed80-4488-11ea-9326-7db8e7719add.png)

**Comment by ManuGooX** [comment]
And this happens too

`[15:53:54] [Skungee Pool Thread #0/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@660591fb, id=69, owner=me.limeglass.skungee.bungeecord.Skungee@6cceb281, task=me.limeglass.skungee.bungeecord.managers.PlayerTimeManager$$Lambda$270/658369552@7cca31fc, delay=0, period=1000, running=true) encountered an exception
java.lang.NullPointerException: null
	at me.limeglass.skungee.bungeecord.managers.PlayerTimeManager.lambda$null$0(PlayerTimeManager.java:38) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_232]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082) ~[?:1.8.0_232]
	at me.limeglass.skungee.bungeecord.managers.PlayerTimeManager.lambda$new$1(PlayerTimeManager.java:31) ~[?:?]
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:a27ee5c:121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]`

**Comment by TheLimeGlass** [comment]
First error is because you're setting Skungee to load on a port that is already in use, that is user error. Try a different port, and remember the port is not the same as the Bungeecord/Server port, it's gotta have it's.own dedicated open port.

Second error will be looked into.

**Comment by ManuGooX** [comment]
Yes, the 1rst error is because I've tried to make a test in another bungeecord server because in my principal bungeecord I've got the second problem with skungee and network variables and skungee skripts are bug.

**Comment by ManuGooX** [comment]
![image](https://user-images.githubusercontent.com/40543551/73593718-721fdd80-4507-11ea-857a-c94d0ce3aedf.png)

I start bungeecord and when it pass 1 minute it send that and all network variable skripts stop working and bugs all skungee skripts.

**Comment by TheLimeGlass** [comment]
Global scripts and network variables will be working, this is not related.

**Comment by ManuGooX** [comment]
I've see and when this error appear in bungee all network variables on /plugins/Skungee/variables remove the contents of variables.csv

**Comment by TheLimeGlass** [comment]
Fixed in next version.

**Comment by ManuGooX** [comment]
Thanks, and when will be the next version released?

**Comment by TheLimeGlass** [comment]
1.0.13 which was just released.

**Comment by ManuGooX** [comment]
Mm I think it happens now too, Do I need to restart all servers with skungee?

**Comment by Zulfen** [comment]
This still occurs for me as well:
https://github.com/Skungee/Skungee/issues/167
